console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[transient_prompt]
  template = '{{if .Root}}⚡ {{end}}🚀 '
  foreground = '#FFD700'
  background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'
    foreground = '#fff'
    powerline_symbol = ''
    background = '#003543'
    type = 'os'
    style = 'powerline'

    [blocks.segments.properties]
      windows = ''

  [[blocks.segments]]
    template = '{{ .UserName }}@{{ .HostName }}'
    foreground = '#d2ff5e'
    powerline_symbol = ''
    background = '#003543'
    type = 'session'
    style = 'powerline'

  [[blocks.segments]]
    template = '  {{ .Path }} '
    foreground = '#003544'
    powerline_symbol = ''
    background = '#0087D8'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    template = ' {{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    foreground = '#193549'
    powerline_symbol = ''
    background = '#d2ff5e'
    type = 'git'
    style = 'powerline'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#f17c37{{ end }}']

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
  
  [[blocks.segments]]
    type = "rust"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#193549"
    background = "#99908a"
    template = "  {{ .Full }} "

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}  '
    foreground = '#242424'
    powerline_symbol = ''
    background = '#f36943'
    type = 'battery'
    style = 'powerline'
    background_templates = ['{{if eq "Charging" .State.String}}#33DD2D{{end}}', '{{if eq "Discharging" .State.String}}#FFCD58{{end}}', '{{if eq "Full" .State.String}}#0476d0{{end}}']
    invert_powerline = true

  [[blocks.segments]]
    type = "spotify"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#1BD760"
    min_width=110

    [blocks.segments.properties]
      playing_icon = " "
      paused_icon = "⏸ "
      stopped_icon = " "

  [[blocks.segments]]
    template = '  {{ .Venv }} '
    foreground = '#003544'
    powerline_symbol = ''
    background = '#0087D8'
    type = 'python'
    style = 'powerline'
    invert_powerline = true

    [blocks.segments.properties]
      display_mode = 'context'
      fetch_virtual_env = true

  [[blocks.segments]]
    type = "kubectl"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#000000"
    background = "#ebcc34"
    template = " {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} "

  [[blocks.segments]]
    type = "bazel"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#ffffff"
    background = "#43a047"

  [[blocks.segments]]
    template = '<#fff>  </>{{ .CurrentDate | date .Format }} '
    foreground = '#fff'
    powerline_symbol = ''
    background = '#003543'
    type = 'time'
    style = 'powerline'
    invert_powerline = true

  [[blocks.segments]]
    type = "upgrade"
    style = "plain"
    foreground = "#111111"
    background = "#FFD664"

    [blocks.segments.properties]
    cache_duration = "168h"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = ' ⚡ '
    foreground = '#FFD700'
    type = 'root'
    style = 'plain'

  [[blocks.segments]]
    template = '> '
    foreground = '#f1184c'
    type = 'text'
    style = 'plain'
