# SOPS configuration
# Replace the placeholder with your actual age public key
# Get your public key from: cat ~/.config/sops/age/keys.txt | grep "public key"

keys:
  # Amaterasu
  - &primary age1mr26snwm6pyq9pavjj6suu0efpvfugs3x4f8mak998d0cfz30p3qs66lcv
  # Add more keys for other machines:
  # - &secondary age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *primary
          # - *secondary  # Uncomment when adding more machines
